services:
  lokilens:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MCP_SERVER_URL=http://localhost:8000
    volumes:
      - ./logs:/app/logs
      - .:/app
    restart: unless-stopped 