services:
  - type: web
    name: lokilens
    env: docker
    plan: free  # Change to 'starter' or higher for production
    dockerfilePath: server/Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_SESSION_TOKEN
        sync: false
      - key: BUCKET_NAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
    ports:
      - 8000

  - type: web
    name: mcp-client
    env: docker
    plan: free  # Change to 'starter' or higher for production
    dockerfilePath: client/Dockerfile
    buildCommand: ""
    startCommand: uvicorn mcp_client_api:app --host 0.0.0.0 --port 9000
    autoDeploy: true
    envVars:
      - key: MCP_SERVER_URL
        value: "https://lokilens-1.onrender.com/mcp"
      - key: OPENAI_API_KEY
        sync: false
    ports:
      - 9000 